default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: GWI_development

test:
  <<: *default
  database: GWI_test

production:
  <<: *default
  database: GWI_production
  username: postgres
  password: <%= ENV['GWI_DATABASE_PASSWORD'] %>
